PassportGrantCounty/Controllers/ExperienceController.cs
using Passport.Data;
using Passport.Services;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Passport.Models.ExperienceModels;

namespace PassportGrantCounty.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ExperienceController : Controller
    {
        private readonly ExperienceService _experienceService;
        private readonly ApplicationDbContext _ctx;
        public ExperienceController()
        {
            _experienceService = new ExperienceService();
            _ctx = new ApplicationDbContext();
        }
        // GET: Experience
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.Name = String.IsNullOrEmpty(sortOrder) ? "nameDescending" : "";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;

            var model = _experienceService.GetAllExperiences();
            if (!String.IsNullOrEmpty(searchString))
            {
                model = model.Where(e => e.Name.ToLower().Contains(searchString.ToLower()));
            }
            switch (sortOrder)
            {
                case "nameDescending":
                    model = model.OrderByDescending(m => m.Name);
                    break;
                default: // Name ascending
                    model = model.OrderBy(m => m.Name);
                    break;
            }

            int pageSize = 25;
            int pageNumber = (page ?? 1);

            return View(model.ToPagedList(pageNumber, pageSize));
        }
        // GET: Experience/Details/{id}
        public ActionResult Details(int experienceId)
        {
            var model = _experienceService.GetExperienceDetailViewById(experienceId);
            return View(model);
        }
        // POST: Experience/Delete/{id}
        [HttpPost]
        public ActionResult Delete(int experienceId)
        {
            _experienceService.Delete(experienceId);
            TempData["SaveResult"] = "Experience deleted";
            return RedirectToAction("Index");
        }
        // GET: Experience/Create
        public ActionResult Create()
        {
            return View();
        }
        // POST: Experience/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ExperienceCreateModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            if (_experienceService.Create(model))
            {
                TempData["SaveResult"] = "Experience created";
                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", "Unable to create experience");
            return View(model);
        }
        // GET: Experience/Edit/{id}
        public ActionResult Edit(int experienceId)
        {
            var detail = _experienceService.GetExperienceDetailById(experienceId);
            var model = new ExperienceUpdateModel
            {
                ExperienceId = detail.ExperienceId,
                Name = detail.Name,
                ChallengeScoreIncrease = detail.ChallengeScoreIncrease,
            };
            return View(model);
        }
        // POST: Experience/Edit/{id}
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ExperienceUpdateModel model, int experienceId)
        {
            if (model.ExperienceId != experienceId)
            {
                ModelState.AddModelError("", "Id Mismatch");
                return View(model);
            }
            if (_experienceService.Edit(model))
            {
                TempData["SaveResult"] = "Experience edited";
                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", "Unable to edit experience");
            return View(model);
        }
    }
}

PassportGrantCounty/Views/Experience/Details.cshtml
@model Passport.Models.ExperienceModels.ExperienceDetailModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>ExperienceDetailModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ExperienceId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ExperienceId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

PassportGrantCounty/Views/Experience/Edit.cshtml
@model Passport.Models.ExperienceModels.ExperienceUpdateModel

@{
    ViewBag.Title = "Edit";
}

<div class="pageTitle adminTitle">
    <h1>Edit: <i>@Html.DisplayFor(model => model.Name)</i></h1>
</div>

<div class="container-md">


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>ExperienceUpdateModel</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.ExperienceId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ExperienceId, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ExperienceId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

PassportGrantCounty/Views/Experience/Index.cshtml
@model PagedList.IPagedList<Passport.Models.ExperienceModels.ExperienceListModel>
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Index";
}

<div class="pageTitle adminTitle">
    <h1>Experiences</h1>
</div>

<div class="container-md">
    <div class="row">
        @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
        {
            <div class="offset-lg-1 col-5">
                <div class="indexCreateLink">
                    <button type="button" value="createExperience" class="btn btn-primary">@Html.ActionLink("Create an Experience", "Create", "Experience")</button>
                </div>
            </div>
            <div class="col-lg-5 col-7">
                <div class="searchBar">
                    @using (Html.BeginForm("Index", "Experience", FormMethod.Get))
                    {
                        <div class="input-group">
                            @Html.TextBox("SearchString", ViewBag.CurrentFilter as string, new { @class = "form-control", style = "border-color: #FFBC0A;", placeholder = "Search ... " })
                            <div class="input-group-append">
                                <button type="submit" class="btn btn-primary"><i class="fas fa-search"></i></button>
                            </div>
                        </div>
                    }
                </div>
            </div>
        }
        else
        {
            <div class="col-lg-11 col-12">
                <div class="searchBar">
                    @using (Html.BeginForm("Index", "Experience", FormMethod.Get))
                    {
                        <div class="input-group">
                            @Html.TextBox("SearchString", ViewBag.CurrentFilter as string, new { @class = "form-control", style = "border-color: #FFBC0A;", placeholder = "Search ... " })
                            <div class="input-group-append">
                                <button type="submit" class="btn btn-primary"><i class="fas fa-search"></i></button>
                            </div>
                        </div>
                    }
                </div>
            </div>

        }
    </div>



    <div class="row">
        <div class=" col-lg-10 offset-lg-1">
            <table class="table">
                <tr>
                    <th>
                        @Html.ActionLink("Name", "Index", new { sortOrder = ViewBag.NameSortParam, currentFilter = ViewBag.CurrentFilter }, new { @class = "linkStandard" })
                    </th>
                    <th>
                    </th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.ActionLink(item.Name, "Details", new { ExperienceId = item.ExperienceId }, new { @class = "linkStandard" })
                        </td>
                        <td class="listButtonsContainer">
                            <div class="listButtons">
                                <ul class="horizontalList">
                                    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                                    {
                                        <li><button type="button" class="btn btn-cancel btn-sm deleteItem indexButton" data-id="@item.ExperienceId"><i class="far fa-trash-alt"></i></button></li>
                                        <li><button type="button" class="btn btn-primary btn-sm indexButton"><a href="/Experience/Details/@item.ExperienceId"><i class="fas fa-info"></i></a></button></li>
                                        <li><button type="button" class="btn btn-primary btn-sm indexButton"><a href="/Experience/Edit/@item.ExperienceId"><i class="fas fa-edit"></i></a></button></li>
                                    }
                                    else
                                    {
                                        <li><button type="button" class="btn btn-primary btn-sm indexButton"><a href="/Experience/Details/@item.ExperienceId"><i class="fas fa-info"></i></a></button></li>
                                    }
                                </ul>
                            </div>
                        </td>
                    </tr>
                }

            </table>
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        $(document).ready(function () {
            $('.deleteItem').on('click', function () {
                var itemId = $(this).attr('data-id');
                var message = confirm('Are you sure you wish to reset this item?');
                if (message) {
                    $.ajax({
                        type: 'POST',
                        url: '@Url.Action("Delete", "Experience")',
                        data: { itemId },
                        success: function () {
                            setTimeout(function () { location.reload(); }, 1000);
                        },
                        error: function () {
                            alert('Unable to delete item');
                        }
                    })
                }
            })
        })
    </script>