PassportGrantCounty/Controllers/StampController.cs
using PagedList;
using Passport.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PassportGrantCounty.Controllers
{
    public class StampController : Controller
    {
        private readonly StampService _stampService;
        public StampController()
        {
            _stampService = new StampService();
        }
        // GET: Stamp
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.CreatorSortParam = sortOrder == "Explorer" ? "explorerDescending" : "Explorer";
            ViewBag.NameSortParam = String.IsNullOrEmpty(sortOrder) ? "nameDescending" : "";
            ViewBag.StampLevelSortParam = sortOrder == "StampLevel" ? "stampLevelDescending" : "StampLevel";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;

            var model = _stampService.GetAllStamps();
            if (!String.IsNullOrEmpty(searchString))
            {
                model = model.Where(e => e.Name.ToLower().Contains(searchString.ToLower()) || e.Explorer.ToLower().Contains(searchString.ToLower()));
            }
            switch (sortOrder)
            {
                case "Explorer":
                    model = model.OrderBy(m => m.Explorer);
                    break;
                case "explorerDescending":
                    model = model.OrderByDescending(m => m.Explorer);
                    break;
                case "StampLevel":
                    model = model.OrderBy(m => m.StampLevel);
                    break;
                case "stampLevelDescending":
                    model = model.OrderByDescending(m => m.StampLevel);
                    break;
                case "nameDescending":
                    model = model.OrderByDescending(m => m.Name);
                    break;
                default: // Name ascending
                    model = model.OrderBy(m => m.Name);
                    break;
            }

            int pageSize = 25;
            int pageNumber = (page ?? 1);

            return View(model.ToPagedList(pageNumber, pageSize));
        }
        // GET: Stamp/Details/{id}
        public ActionResult Details(int stampId)
        {
            var model = _stampService.GetStampDetailViewById(stampId);
            return View(model);
        }
    }
}

PassportGrantCounty/Views/Stamp/Details.cshtml
@model Passport.Models.StampModels.StampDetailModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>StampDetailModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.StampId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StampId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Explorer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Explorer)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StampLevel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StampLevel)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

PassportGrantCounty/Views/Stamp/Index.cshtml
@model PagedList.IPagedList<Passport.Models.StampModels.StampListModel>
@using PagedList;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{ ViewBag.Title = "Stamps"; }
<div class="pageTitle stampTitle">
    <h1>Stamps</h1>
</div>

<div class="container-md">

    <div class="row">
        @if (User.Identity.IsAuthenticated)
        {
    <div class="offset-lg-1 col-5">
        <div class="indexCreateLink">
            <button type="button" value="earnStamp" class="btn btn-primary">@Html.ActionLink("Earn a Stamp", "Earn", "User Stamps")</button>
        </div>
    </div>
                <div class="col-lg-5 col-7">
                    <div class="searchBar">
                        @using (Html.BeginForm("Index", "Stamps", FormMethod.Get))
                        {
        <div class="input-group">
            @Html.TextBox("SearchString", ViewBag.CurrentFilter as string, new { @class = "form-control", style = "border-color: #FFBC0A;", placeholder = "Search ... " })
            <div class="input-group-append">
                <button type="submit" class="btn btn-primary"><i class="fas fa-search"></i></button>
            </div>
        </div>}
                    </div>
                </div> }
                            else
                            {
                <div class="col-lg-11 col-12">
                    <div class="searchBar">
                        @using (Html.BeginForm("Index", "Stamp", FormMethod.Get))
                        {
        <div class="input-group">
            @Html.TextBox("SearchString", ViewBag.CurrentFilter as string, new { @class = "form-control", style = "border-color: #FFBC0A;", placeholder = "Search ... " })
            <div class="input-group-append">
                <button type="submit" class="btn btn-primary"><i class="fas fa-search"></i></button>
            </div>
        </div>}
                    </div>
                </div>}
    </div>

    <div class="row">
        <div class="col-lg-10 offset-lg-1">
            <table class="table stampTable">
                <tr>
                    <th>
                        @Html.ActionLink("Stamp Collection", "Index", new { sortOrder = ViewBag.CollectionSortParam, currentFilter = ViewBag.CurrentFilter }, new { @class = "linkStandard" })
                    </th>
                    <th>
                        @Html.ActionLink("Name", "Index", new { sortOrder = ViewBag.NameSortParam, currentFilter = ViewBag.CurrentFilter }, new { @class = "linkStandard" })
                    </th>
                    <th>
                        @Html.ActionLink("Experiences", "Index", new { sortOrder = ViewBag.ExperiencesSortParam, currentFilter = ViewBag.CurrentFilter }, new { @class = "linkStandard" })
                    </th>
                    <th>
                        @Html.ActionLink("Road Maps", "Index", new { sortOrder = ViewBag.RoadMapsSortParam, currentFilter = ViewBag.CurrentFilter }, new { @class = "linkStandard" })
                    </th>
                    <th>
                    </th>
                </tr>

                @foreach (var item in Model)
                {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.StampId)
        </td>
        <td>
            @Html.ActionLink(item.Name, "Details", new { stampId = item.StampId }, new { @class = "linkStandard" })
        </td>
        <td class="listButtonsContainer">
            <div class="listButtons">
                <ul class="horizontalList">
                    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                    {
                <li><button type="button" class="btn btn-cancel btn-sm deleteItem indexButton" data-id="@item.StampId"><i class="far fa-trash-alt"></i></button></li>
                                    <li><button type="button" class="btn btn-primary btn-sm indexButton"><a href="/Spell/Details/@item.StampId"><i class="fas fa-info"></i></a></button></li>
                                                        <li><button type="button" class="btn btn-primary btn-sm indexButton"><a href="/UserSpell/Edit/@item.StampId"><i class="fas fa-edit"></i></a></button></li>
 }
                                                    else
                                                    {
                                    <li><button type="button" class="btn btn-primary btn-sm indexButton"><a href="/Spell/Details/@item.StampId"><i class="fas fa-info"></i></a></button></li>
}
                </ul>
            </div>
        </td>
    </tr>}
            </table>
        </div>
    </div>
    @if (Model.PageCount > 1)

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        $(document).ready(function () {
            $('.deleteItem').on('click', function () {
                var itemId = $(this).attr('data-id');
                var message = confirm('Are you sure you wish to reset this item?');

                if (message) {
                    $.ajax({
                        type: 'POST',
                        url: '@Url.Action("Delete", "UserStamps")',
                        data: { itemId },
                        success: function () {
                            setTimeout(function () { location.reload(); }, 1000);
                        },
                        error: function () {
                            alert('Unable to delete item');
                        }
                    })
                }
            })
        })
    </script>

}