PassportGrantCounty/Controllers/RoadMapController.cs
using PagedList;
using Passport.Models.RoadMapModels;
using Passport.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PassportGrantCounty.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RoadMapController : Controller
    {
        private readonly RoadMapService _roadMapService;
        public RoadMapController()
        {
            _roadMapService = new RoadMapService();
        }
        // GET: RoadMap
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.Name = String.IsNullOrEmpty(sortOrder) ? "nameDescending" : "";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;

            var model = _roadMapService.GetAllRoadMaps();
            if (!String.IsNullOrEmpty(searchString))
            {
                model = model.Where(e => e.Name.ToLower().Contains(searchString.ToLower()));
            }
            switch (sortOrder)
            {
                case "nameDescending":
                    model = model.OrderByDescending(m => m.Name);
                    break;
                default: // Name ascending
                    model = model.OrderBy(m => m.Name);
                    break;
            }

            int pageSize = 25;
            int pageNumber = (page ?? 1);

            return View(model.ToPagedList(pageNumber, pageSize));
        }
        // GET: RoadMap/Create
        public ActionResult Create()
        {
            return View();
        }
        // POST: RoadMap/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(RoadMapCreateModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            if (_roadMapService.Create(model))
            {
                TempData["SaveResult"] = "Road Map Created";
                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", "Unable to create road map");
            return View(model);
        }
        // GET: RoadMap/Details/{id}
        public ActionResult Details(int roadMapId)
        {
            var model = _roadMapService.GetRoadMapDetailViewById(roadMapId);

            return View(model);
        }
        // POST: RoadMap/Delete/{id}
        [HttpPost]
        public ActionResult Delete(int roadMapId)
        {
            _roadMapService.Delete(roadMapId);
            TempData["SaveResult"] = "RoadMap deleted";
            return RedirectToAction("Index");
        }
        // GET: RoadMap/Edit/{id}
        public ActionResult Edit(int roadMapId)
        {
            var details = _roadMapService.GetRoadMapDetailById(roadMapId);
            var model = new RoadMapUpdateModel
            {
                RoadMapId = details.RoadMapId,
                Name = details.Name,
                Speed = details.Speed,
                IsActive = details.IsActive,
                ChallengeScoreIncrease = details.ChallengeScoreIncrease,
                Experiences = details.Experiences,
            };
            return View(model);
        }
        // POST: RoadMap/Edit/{id}
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(RoadMapUpdateModel model, int roadMapId)
        {
            if (model.RoadMapId != roadMapId)
            {
                ModelState.AddModelError("", "Id Mismatch");
                return View(model);
            }
            if (_roadMapService.Edit(model))
            {
                TempData["SaveResult"] = "RoadMap edited";
                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", "Unable to edit roadMap");
            return View(model);
        }
    }
}

PassportGrantCounty/Views/RoadMap/Create.cshtml
@model Passport.Models.RoadMapModels.RoadMapCreateModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>RoadMapCreateModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Speed, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Speed, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Speed, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsActive)
                    @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PassportGrantCounty/Views/RoadMap/Details.cshtml
@model Passport.Models.RoadMapModels.RoadMapDetailModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>RoadMapDetailModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.RoadMapId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RoadMapId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Speed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Speed)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsActive)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

PassportGrantCounty/Views/RoadMap/Edit.cshtml
@model Passport.Models.RoadMapModels.RoadMapUpdateModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>RoadMapUpdateModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.RoadMapId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RoadMapId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RoadMapId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Speed, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Speed, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Speed, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsActive)
                    @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PassportGrantCounty/Views/RoadMap/Index.cshtml
@model PagedList.IPagedList<Passport.Models.RoadMapModels.RoadMapListModel>
@using PagedList;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />


@{ ViewBag.Title = "Index"; }

<div class="pageTitle adminTitle">
    <h1>Road Maps</h1>
</div>

<div class="container-md">

    <div class="row">

        @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
        {
<div class="offset-lg-1 col-5">
    <div class="indexCreateLink">
        <button type="button" value="startRoadMap" class="btn btn-primary">@Html.ActionLink("Start a Road Map", "Start", "Road Map")</button>
    </div>
</div>
                <div class="col-lg-5 col-7">
                    <div class="searchBar">
                        @using (Html.BeginForm("Index", "RoadMap", FormMethod.Get))
                        {
        <div class="input-group">
            @Html.TextBox("SearchString", ViewBag.CurrentFilter as string, new { @class = "form-control", style = "border-color: #FFBC0A;", placeholder = "Search ... " })
            <div class="input-group-append">
                <button type="submit" class="btn btn-primary"><i class="fas fa-search"></i></button>
            </div>
        </div>}
                    </div>
                </div> }
                            else
                            {
                <div class="col-lg-11 col-12">
                    <div class="searchBar">
                        @using (Html.BeginForm("Index", "Road Map", FormMethod.Get))
                        {
        <div class="input-group">
            @Html.TextBox("SearchString", ViewBag.CurrentFilter as string, new { @class = "form-control", style = "border-color: #FFBC0A;", placeholder = "Search ... " })
            <div class="input-group-append">
                <button type="submit" class="btn btn-primary"><i class="fas fa-search"></i></button>
            </div>
        </div>}
                    </div>
                </div>}
    </div>

    <div class="row">
        <div class=" col-lg-10 offset-lg-1">
            <table class="table">
                <tr>
                    <th>
                        @Html.ActionLink("Name", "Index", new { sortOrder = ViewBag.NameSortParam, currentFilter = ViewBag.CurrentFilter }, new { @class = "linkStandard" })
                    </th>
                    <th>
                    </th>
                </tr>

                @foreach (var item in Model)
                {
    <tr>
        <td>
            @Html.ActionLink(item.Name, "Details", new { roadMapId = item.RoadMapId }, new { @class = "linkStandard" })
        </td>
        <td class="listButtonsContainer">
            <div class="listButtons">
                <ul class="horizontalList">
                    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                    {
    <li><button type="button" class="btn btn-cancel btn-sm deleteItem indexButton" data-id="@item.RoadMapId"><i class="far fa-trash-alt"></i></button></li>
                        <li><button type="button" class="btn btn-primary btn-sm indexButton"><a href="/RoadMap/Details/@item.RoadMapId"><i class="fas fa-info"></i></a></button></li>
                                            <li><button type="button" class="btn btn-primary btn-sm indexButton"><a href="/RoadMap/Edit/@item.RoadMapId"><i class="fas fa-edit"></i></a></button></li> }
                                                            else
                                                            {
                                            <li><button type="button" class="btn btn-primary btn-sm indexButton"><a href="/RoadMap/Details/@item.RoadMapId"><i class="fas fa-info"></i></a></button></li>}
                </ul>
            </div>
        </td>
    </tr>}

            </table>
        </div>
    </div>
    @if (Model.PageCount > 1)
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        $(document).ready(function () {
            $('.deleteItem').on('click', function () {
                var itemId = $(this).attr('data-id');
                var message = confirm('Are you sure you wish to reset this item?');

                if (message) {
                    $.ajax({
                        type: 'POST',
                        url: '@Url.Action("Delete", "RoadMap")',
                        data: { itemId },
                        success: function () {
                            setTimeout(function () { location.reload(); }, 1000);
                        },
                        error: function () {
                            alert('Unable to delete item');
                        }
                    })
                }
            })
        })
    </script>
}